const M_REQUEST_REMOTE_CHANGES = 'requestUpdates';
const M_SENDABLE = 'sendable';
const M_SEND_LOCAL_CHANGES = 'update';
const M_NEW_VERSION = 'newVersion';
const M_RECV_REMOTE_CHANGES = 'updates';
const M_CONFIRMED = 'confirmed';
const M_INVALID_VERSION = 'invalidVersion';
const M_TIMEOUT = 'timeout';

const E_APPLY_CHANGES = 'APPLY_CHANGES';
const E_REQUEST_LOCAL_SYNC = 'REQUEST_LOCAL_SYNC';
const E_SEND_REMOTE_CHANGES = 'SEND_REMOTE_CHANGES';
const E_SEND_LOCAL_CHANGES = 'SEND_LOCAL_CHANGES';
const E_TIMEOUT = 'TIMEOUT';

export {
	M_REQUEST_REMOTE_CHANGES,
	M_SENDABLE,
	M_SEND_LOCAL_CHANGES,
	M_NEW_VERSION,
	M_RECV_REMOTE_CHANGES,
	M_CONFIRMED,
	M_INVALID_VERSION,
	M_TIMEOUT,

	E_APPLY_CHANGES,
	E_REQUEST_LOCAL_SYNC,
	E_SEND_REMOTE_CHANGES,
	E_SEND_LOCAL_CHANGES,
	E_TIMEOUT
};